name: pangeo-bench
channels:
  - conda-forge
dependencies:
  - click
  - dask-jobqueue
  - dask-labextension
  - dask>=2.3
  - holoviews
  - hvplot
  - ipywidgets
  - jupyterlab
  - matplotlib
  - netcdf4
  - nodejs
  - numpy
  - pandas
  - python=3.7
  - scipy
  - setuptools
  - xarray>=0.12.3
  - zarr
